#!/usr/bin/expect -f

set timeout -1

spawn acpi_listen
expect {
	"button/lid LID close" {
		system dbus-send --session --dest=org.gnome.ScreenSaver --type=method_call \
          /org/gnome/ScreenSaver org.gnome.ScreenSaver.SetActive boolean:true
          	exp_continue
		} "button/lid LID open" {
		system xdg-screensaver reset
		exp_continue
		}
}
