#!/usr/bin/expect -f

set timeout -1

spawn acpi_listen
expect {
	"button/lid LID close" {
		system xdg-screensaver activate
          	exp_continue
		} "button/lid LID open" {
		system xdg-screensaver reset
		exp_continue
		}
}
